### ISSUE TITLE
paper corrigendum？

### ISSUE THREAD

**Issue by wsy-yjys** [byyx666/ArchCraft#1]
> For Class IL, we follow PyCIL [Zhou et al., 2023] to train the model by 200 epochs in the first task and 70 epochs in the subsequent tasks.

![image](https://github.com/user-attachments/assets/2f0d087f-5c5e-4a58-a8dc-e99ba447de60)

![image](https://github.com/user-attachments/assets/a080370e-759b-4613-8744-5923963c1505)

**Comment by byyx666** [comment]
Please use the values published in the paper, I have updated replay.py to be consistent with the paper.
